# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 02:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zybooEvents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('fromDatetime', models.DateTimeField()),
                ('toDatetime', models.DateTimeField()),
                ('addPromo', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredPubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address_street_num', models.IntegerField()),
                ('address_street_name', models.TextField(max_length=64)),
                ('address_line2', models.TextField(max_length=128)),
                ('address_city', models.CharField(max_length=64)),
                ('address_state', models.CharField(max_length=64)),
                ('address_zipcode', models.CharField(max_length=16)),
                ('address_country', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='pubName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zybooEvents.RegisteredPubs'),
        ),
    ]
